// GENERATED by scripts/generate-country-data.mjs. Do not edit by hand.
// Country names and dial codes, extracted so the package does not ship the
// full world-countries dataset. Regenerate when the libphonenumber region set
// or world-countries metadata changes.

export interface CountryDatum {
  name: string
  dialCodes: string[]
}

export const COUNTRY_DATA: Record<string, CountryDatum> = {
  "AC": {
    "name": "Ascension Island",
    "dialCodes": [
      "+247"
    ]
  },
  "AD": {
    "name": "Andorra",
    "dialCodes": [
      "+376"
    ]
  },
  "AE": {
    "name": "United Arab Emirates",
    "dialCodes": [
      "+971"
    ]
  },
  "AF": {
    "name": "Afghanistan",
    "dialCodes": [
      "+93"
    ]
  },
  "AG": {
    "name": "Antigua and Barbuda",
    "dialCodes": [
      "+1",
      "+1268"
    ]
  },
  "AI": {
    "name": "Anguilla",
    "dialCodes": [
      "+1",
      "+1264"
    ]
  },
  "AL": {
    "name": "Albania",
    "dialCodes": [
      "+355"
    ]
  },
  "AM": {
    "name": "Armenia",
    "dialCodes": [
      "+374"
    ]
  },
  "AO": {
    "name": "Angola",
    "dialCodes": [
      "+244"
    ]
  },
  "AR": {
    "name": "Argentina",
    "dialCodes": [
      "+54"
    ]
  },
  "AS": {
    "name": "American Samoa",
    "dialCodes": [
      "+1",
      "+1684"
    ]
  },
  "AT": {
    "name": "Austria",
    "dialCodes": [
      "+43"
    ]
  },
  "AU": {
    "name": "Australia",
    "dialCodes": [
      "+61"
    ]
  },
  "AW": {
    "name": "Aruba",
    "dialCodes": [
      "+297"
    ]
  },
  "AX": {
    "name": "Åland Islands",
    "dialCodes": [
      "+358",
      "+35818"
    ]
  },
  "AZ": {
    "name": "Azerbaijan",
    "dialCodes": [
      "+994"
    ]
  },
  "BA": {
    "name": "Bosnia and Herzegovina",
    "dialCodes": [
      "+387"
    ]
  },
  "BB": {
    "name": "Barbados",
    "dialCodes": [
      "+1",
      "+1246"
    ]
  },
  "BD": {
    "name": "Bangladesh",
    "dialCodes": [
      "+880"
    ]
  },
  "BE": {
    "name": "Belgium",
    "dialCodes": [
      "+32"
    ]
  },
  "BF": {
    "name": "Burkina Faso",
    "dialCodes": [
      "+226"
    ]
  },
  "BG": {
    "name": "Bulgaria",
    "dialCodes": [
      "+359"
    ]
  },
  "BH": {
    "name": "Bahrain",
    "dialCodes": [
      "+973"
    ]
  },
  "BI": {
    "name": "Burundi",
    "dialCodes": [
      "+257"
    ]
  },
  "BJ": {
    "name": "Benin",
    "dialCodes": [
      "+229"
    ]
  },
  "BL": {
    "name": "Saint Barthélemy",
    "dialCodes": [
      "+590"
    ]
  },
  "BM": {
    "name": "Bermuda",
    "dialCodes": [
      "+1",
      "+1441"
    ]
  },
  "BN": {
    "name": "Brunei",
    "dialCodes": [
      "+673"
    ]
  },
  "BO": {
    "name": "Bolivia",
    "dialCodes": [
      "+591"
    ]
  },
  "BQ": {
    "name": "Caribbean Netherlands",
    "dialCodes": [
      "+599"
    ]
  },
  "BR": {
    "name": "Brazil",
    "dialCodes": [
      "+55"
    ]
  },
  "BS": {
    "name": "Bahamas",
    "dialCodes": [
      "+1",
      "+1242"
    ]
  },
  "BT": {
    "name": "Bhutan",
    "dialCodes": [
      "+975"
    ]
  },
  "BW": {
    "name": "Botswana",
    "dialCodes": [
      "+267"
    ]
  },
  "BY": {
    "name": "Belarus",
    "dialCodes": [
      "+375"
    ]
  },
  "BZ": {
    "name": "Belize",
    "dialCodes": [
      "+501"
    ]
  },
  "CA": {
    "name": "Canada",
    "dialCodes": [
      "+1",
      "+1204",
      "+1226",
      "+1236",
      "+1249",
      "+1250",
      "+1263",
      "+1289",
      "+1306",
      "+1343",
      "+1354",
      "+1365",
      "+1367",
      "+1368",
      "+1382",
      "+1387",
      "+1403",
      "+1416",
      "+1418",
      "+1428",
      "+1431",
      "+1437",
      "+1438",
      "+1450",
      "+1468",
      "+1474",
      "+1506",
      "+1514",
      "+1519",
      "+1548",
      "+1579",
      "+1581",
      "+1584",
      "+1587",
      "+1600",
      "+1604",
      "+1613",
      "+1622",
      "+1633",
      "+1639",
      "+1644",
      "+1647",
      "+1655",
      "+1672",
      "+1677",
      "+1683",
      "+1688",
      "+1705",
      "+1709",
      "+1742",
      "+1753",
      "+1778",
      "+1780",
      "+1782",
      "+1807",
      "+1819",
      "+1825",
      "+1867",
      "+1873",
      "+1879",
      "+1902",
      "+1905",
      "+1942"
    ]
  },
  "CC": {
    "name": "Cocos (Keeling) Islands",
    "dialCodes": [
      "+61"
    ]
  },
  "CD": {
    "name": "DR Congo",
    "dialCodes": [
      "+243"
    ]
  },
  "CF": {
    "name": "Central African Republic",
    "dialCodes": [
      "+236"
    ]
  },
  "CG": {
    "name": "Republic of the Congo",
    "dialCodes": [
      "+242"
    ]
  },
  "CH": {
    "name": "Switzerland",
    "dialCodes": [
      "+41"
    ]
  },
  "CI": {
    "name": "Ivory Coast",
    "dialCodes": [
      "+225"
    ]
  },
  "CK": {
    "name": "Cook Islands",
    "dialCodes": [
      "+682"
    ]
  },
  "CL": {
    "name": "Chile",
    "dialCodes": [
      "+56"
    ]
  },
  "CM": {
    "name": "Cameroon",
    "dialCodes": [
      "+237"
    ]
  },
  "CN": {
    "name": "China",
    "dialCodes": [
      "+86"
    ]
  },
  "CO": {
    "name": "Colombia",
    "dialCodes": [
      "+57"
    ]
  },
  "CR": {
    "name": "Costa Rica",
    "dialCodes": [
      "+506"
    ]
  },
  "CU": {
    "name": "Cuba",
    "dialCodes": [
      "+53"
    ]
  },
  "CV": {
    "name": "Cape Verde",
    "dialCodes": [
      "+238"
    ]
  },
  "CW": {
    "name": "Curaçao",
    "dialCodes": [
      "+599"
    ]
  },
  "CX": {
    "name": "Christmas Island",
    "dialCodes": [
      "+61"
    ]
  },
  "CY": {
    "name": "Cyprus",
    "dialCodes": [
      "+357"
    ]
  },
  "CZ": {
    "name": "Czechia",
    "dialCodes": [
      "+420"
    ]
  },
  "DE": {
    "name": "Germany",
    "dialCodes": [
      "+49"
    ]
  },
  "DJ": {
    "name": "Djibouti",
    "dialCodes": [
      "+253"
    ]
  },
  "DK": {
    "name": "Denmark",
    "dialCodes": [
      "+45"
    ]
  },
  "DM": {
    "name": "Dominica",
    "dialCodes": [
      "+1",
      "+1767"
    ]
  },
  "DO": {
    "name": "Dominican Republic",
    "dialCodes": [
      "+1",
      "+1809",
      "+1829",
      "+1849"
    ]
  },
  "DZ": {
    "name": "Algeria",
    "dialCodes": [
      "+213"
    ]
  },
  "EC": {
    "name": "Ecuador",
    "dialCodes": [
      "+593"
    ]
  },
  "EE": {
    "name": "Estonia",
    "dialCodes": [
      "+372"
    ]
  },
  "EG": {
    "name": "Egypt",
    "dialCodes": [
      "+20"
    ]
  },
  "EH": {
    "name": "Western Sahara",
    "dialCodes": [
      "+212",
      "+2125288",
      "+2125289"
    ]
  },
  "ER": {
    "name": "Eritrea",
    "dialCodes": [
      "+291"
    ]
  },
  "ES": {
    "name": "Spain",
    "dialCodes": [
      "+34"
    ]
  },
  "ET": {
    "name": "Ethiopia",
    "dialCodes": [
      "+251"
    ]
  },
  "FI": {
    "name": "Finland",
    "dialCodes": [
      "+358"
    ]
  },
  "FJ": {
    "name": "Fiji",
    "dialCodes": [
      "+679"
    ]
  },
  "FK": {
    "name": "Falkland Islands",
    "dialCodes": [
      "+500"
    ]
  },
  "FM": {
    "name": "Micronesia",
    "dialCodes": [
      "+691"
    ]
  },
  "FO": {
    "name": "Faroe Islands",
    "dialCodes": [
      "+298"
    ]
  },
  "FR": {
    "name": "France",
    "dialCodes": [
      "+33"
    ]
  },
  "GA": {
    "name": "Gabon",
    "dialCodes": [
      "+241"
    ]
  },
  "GB": {
    "name": "United Kingdom",
    "dialCodes": [
      "+44"
    ]
  },
  "GD": {
    "name": "Grenada",
    "dialCodes": [
      "+1",
      "+1473"
    ]
  },
  "GE": {
    "name": "Georgia",
    "dialCodes": [
      "+995"
    ]
  },
  "GF": {
    "name": "French Guiana",
    "dialCodes": [
      "+594"
    ]
  },
  "GG": {
    "name": "Guernsey",
    "dialCodes": [
      "+44"
    ]
  },
  "GH": {
    "name": "Ghana",
    "dialCodes": [
      "+233"
    ]
  },
  "GI": {
    "name": "Gibraltar",
    "dialCodes": [
      "+350"
    ]
  },
  "GL": {
    "name": "Greenland",
    "dialCodes": [
      "+299"
    ]
  },
  "GM": {
    "name": "Gambia",
    "dialCodes": [
      "+220"
    ]
  },
  "GN": {
    "name": "Guinea",
    "dialCodes": [
      "+224"
    ]
  },
  "GP": {
    "name": "Guadeloupe",
    "dialCodes": [
      "+590"
    ]
  },
  "GQ": {
    "name": "Equatorial Guinea",
    "dialCodes": [
      "+240"
    ]
  },
  "GR": {
    "name": "Greece",
    "dialCodes": [
      "+30"
    ]
  },
  "GT": {
    "name": "Guatemala",
    "dialCodes": [
      "+502"
    ]
  },
  "GU": {
    "name": "Guam",
    "dialCodes": [
      "+1",
      "+1671"
    ]
  },
  "GW": {
    "name": "Guinea-Bissau",
    "dialCodes": [
      "+245"
    ]
  },
  "GY": {
    "name": "Guyana",
    "dialCodes": [
      "+592"
    ]
  },
  "HK": {
    "name": "Hong Kong",
    "dialCodes": [
      "+852"
    ]
  },
  "HN": {
    "name": "Honduras",
    "dialCodes": [
      "+504"
    ]
  },
  "HR": {
    "name": "Croatia",
    "dialCodes": [
      "+385"
    ]
  },
  "HT": {
    "name": "Haiti",
    "dialCodes": [
      "+509"
    ]
  },
  "HU": {
    "name": "Hungary",
    "dialCodes": [
      "+36"
    ]
  },
  "ID": {
    "name": "Indonesia",
    "dialCodes": [
      "+62"
    ]
  },
  "IE": {
    "name": "Ireland",
    "dialCodes": [
      "+353"
    ]
  },
  "IL": {
    "name": "Israel",
    "dialCodes": [
      "+972"
    ]
  },
  "IM": {
    "name": "Isle of Man",
    "dialCodes": [
      "+44"
    ]
  },
  "IN": {
    "name": "India",
    "dialCodes": [
      "+91"
    ]
  },
  "IO": {
    "name": "British Indian Ocean Territory",
    "dialCodes": [
      "+246"
    ]
  },
  "IQ": {
    "name": "Iraq",
    "dialCodes": [
      "+964"
    ]
  },
  "IR": {
    "name": "Iran",
    "dialCodes": [
      "+98"
    ]
  },
  "IS": {
    "name": "Iceland",
    "dialCodes": [
      "+354"
    ]
  },
  "IT": {
    "name": "Italy",
    "dialCodes": [
      "+39"
    ]
  },
  "JE": {
    "name": "Jersey",
    "dialCodes": [
      "+44"
    ]
  },
  "JM": {
    "name": "Jamaica",
    "dialCodes": [
      "+1",
      "+1876"
    ]
  },
  "JO": {
    "name": "Jordan",
    "dialCodes": [
      "+962"
    ]
  },
  "JP": {
    "name": "Japan",
    "dialCodes": [
      "+81"
    ]
  },
  "KE": {
    "name": "Kenya",
    "dialCodes": [
      "+254"
    ]
  },
  "KG": {
    "name": "Kyrgyzstan",
    "dialCodes": [
      "+996"
    ]
  },
  "KH": {
    "name": "Cambodia",
    "dialCodes": [
      "+855"
    ]
  },
  "KI": {
    "name": "Kiribati",
    "dialCodes": [
      "+686"
    ]
  },
  "KM": {
    "name": "Comoros",
    "dialCodes": [
      "+269"
    ]
  },
  "KN": {
    "name": "Saint Kitts and Nevis",
    "dialCodes": [
      "+1",
      "+1869"
    ]
  },
  "KP": {
    "name": "North Korea",
    "dialCodes": [
      "+850"
    ]
  },
  "KR": {
    "name": "South Korea",
    "dialCodes": [
      "+82"
    ]
  },
  "KW": {
    "name": "Kuwait",
    "dialCodes": [
      "+965"
    ]
  },
  "KY": {
    "name": "Cayman Islands",
    "dialCodes": [
      "+1",
      "+1345"
    ]
  },
  "KZ": {
    "name": "Kazakhstan",
    "dialCodes": [
      "+7",
      "+76",
      "+77"
    ]
  },
  "LA": {
    "name": "Laos",
    "dialCodes": [
      "+856"
    ]
  },
  "LB": {
    "name": "Lebanon",
    "dialCodes": [
      "+961"
    ]
  },
  "LC": {
    "name": "Saint Lucia",
    "dialCodes": [
      "+1",
      "+1758"
    ]
  },
  "LI": {
    "name": "Liechtenstein",
    "dialCodes": [
      "+423"
    ]
  },
  "LK": {
    "name": "Sri Lanka",
    "dialCodes": [
      "+94"
    ]
  },
  "LR": {
    "name": "Liberia",
    "dialCodes": [
      "+231"
    ]
  },
  "LS": {
    "name": "Lesotho",
    "dialCodes": [
      "+266"
    ]
  },
  "LT": {
    "name": "Lithuania",
    "dialCodes": [
      "+370"
    ]
  },
  "LU": {
    "name": "Luxembourg",
    "dialCodes": [
      "+352"
    ]
  },
  "LV": {
    "name": "Latvia",
    "dialCodes": [
      "+371"
    ]
  },
  "LY": {
    "name": "Libya",
    "dialCodes": [
      "+218"
    ]
  },
  "MA": {
    "name": "Morocco",
    "dialCodes": [
      "+212"
    ]
  },
  "MC": {
    "name": "Monaco",
    "dialCodes": [
      "+377"
    ]
  },
  "MD": {
    "name": "Moldova",
    "dialCodes": [
      "+373"
    ]
  },
  "ME": {
    "name": "Montenegro",
    "dialCodes": [
      "+382"
    ]
  },
  "MF": {
    "name": "Saint Martin",
    "dialCodes": [
      "+590"
    ]
  },
  "MG": {
    "name": "Madagascar",
    "dialCodes": [
      "+261"
    ]
  },
  "MH": {
    "name": "Marshall Islands",
    "dialCodes": [
      "+692"
    ]
  },
  "MK": {
    "name": "North Macedonia",
    "dialCodes": [
      "+389"
    ]
  },
  "ML": {
    "name": "Mali",
    "dialCodes": [
      "+223"
    ]
  },
  "MM": {
    "name": "Myanmar",
    "dialCodes": [
      "+95"
    ]
  },
  "MN": {
    "name": "Mongolia",
    "dialCodes": [
      "+976"
    ]
  },
  "MO": {
    "name": "Macau",
    "dialCodes": [
      "+853"
    ]
  },
  "MP": {
    "name": "Northern Mariana Islands",
    "dialCodes": [
      "+1",
      "+1670"
    ]
  },
  "MQ": {
    "name": "Martinique",
    "dialCodes": [
      "+596"
    ]
  },
  "MR": {
    "name": "Mauritania",
    "dialCodes": [
      "+222"
    ]
  },
  "MS": {
    "name": "Montserrat",
    "dialCodes": [
      "+1",
      "+1664"
    ]
  },
  "MT": {
    "name": "Malta",
    "dialCodes": [
      "+356"
    ]
  },
  "MU": {
    "name": "Mauritius",
    "dialCodes": [
      "+230"
    ]
  },
  "MV": {
    "name": "Maldives",
    "dialCodes": [
      "+960"
    ]
  },
  "MW": {
    "name": "Malawi",
    "dialCodes": [
      "+265"
    ]
  },
  "MX": {
    "name": "Mexico",
    "dialCodes": [
      "+52"
    ]
  },
  "MY": {
    "name": "Malaysia",
    "dialCodes": [
      "+60"
    ]
  },
  "MZ": {
    "name": "Mozambique",
    "dialCodes": [
      "+258"
    ]
  },
  "NA": {
    "name": "Namibia",
    "dialCodes": [
      "+264"
    ]
  },
  "NC": {
    "name": "New Caledonia",
    "dialCodes": [
      "+687"
    ]
  },
  "NE": {
    "name": "Niger",
    "dialCodes": [
      "+227"
    ]
  },
  "NF": {
    "name": "Norfolk Island",
    "dialCodes": [
      "+672"
    ]
  },
  "NG": {
    "name": "Nigeria",
    "dialCodes": [
      "+234"
    ]
  },
  "NI": {
    "name": "Nicaragua",
    "dialCodes": [
      "+505"
    ]
  },
  "NL": {
    "name": "Netherlands",
    "dialCodes": [
      "+31"
    ]
  },
  "NO": {
    "name": "Norway",
    "dialCodes": [
      "+47"
    ]
  },
  "NP": {
    "name": "Nepal",
    "dialCodes": [
      "+977"
    ]
  },
  "NR": {
    "name": "Nauru",
    "dialCodes": [
      "+674"
    ]
  },
  "NU": {
    "name": "Niue",
    "dialCodes": [
      "+683"
    ]
  },
  "NZ": {
    "name": "New Zealand",
    "dialCodes": [
      "+64"
    ]
  },
  "OM": {
    "name": "Oman",
    "dialCodes": [
      "+968"
    ]
  },
  "PA": {
    "name": "Panama",
    "dialCodes": [
      "+507"
    ]
  },
  "PE": {
    "name": "Peru",
    "dialCodes": [
      "+51"
    ]
  },
  "PF": {
    "name": "French Polynesia",
    "dialCodes": [
      "+689"
    ]
  },
  "PG": {
    "name": "Papua New Guinea",
    "dialCodes": [
      "+675"
    ]
  },
  "PH": {
    "name": "Philippines",
    "dialCodes": [
      "+63"
    ]
  },
  "PK": {
    "name": "Pakistan",
    "dialCodes": [
      "+92"
    ]
  },
  "PL": {
    "name": "Poland",
    "dialCodes": [
      "+48"
    ]
  },
  "PM": {
    "name": "Saint Pierre and Miquelon",
    "dialCodes": [
      "+508"
    ]
  },
  "PR": {
    "name": "Puerto Rico",
    "dialCodes": [
      "+1",
      "+1787",
      "+1939"
    ]
  },
  "PS": {
    "name": "Palestine",
    "dialCodes": [
      "+970"
    ]
  },
  "PT": {
    "name": "Portugal",
    "dialCodes": [
      "+351"
    ]
  },
  "PW": {
    "name": "Palau",
    "dialCodes": [
      "+680"
    ]
  },
  "PY": {
    "name": "Paraguay",
    "dialCodes": [
      "+595"
    ]
  },
  "QA": {
    "name": "Qatar",
    "dialCodes": [
      "+974"
    ]
  },
  "RE": {
    "name": "Réunion",
    "dialCodes": [
      "+262"
    ]
  },
  "RO": {
    "name": "Romania",
    "dialCodes": [
      "+40"
    ]
  },
  "RS": {
    "name": "Serbia",
    "dialCodes": [
      "+381"
    ]
  },
  "RU": {
    "name": "Russia",
    "dialCodes": [
      "+7",
      "+73",
      "+74",
      "+75",
      "+78",
      "+79"
    ]
  },
  "RW": {
    "name": "Rwanda",
    "dialCodes": [
      "+250"
    ]
  },
  "SA": {
    "name": "Saudi Arabia",
    "dialCodes": [
      "+966"
    ]
  },
  "SB": {
    "name": "Solomon Islands",
    "dialCodes": [
      "+677"
    ]
  },
  "SC": {
    "name": "Seychelles",
    "dialCodes": [
      "+248"
    ]
  },
  "SD": {
    "name": "Sudan",
    "dialCodes": [
      "+249"
    ]
  },
  "SE": {
    "name": "Sweden",
    "dialCodes": [
      "+46"
    ]
  },
  "SG": {
    "name": "Singapore",
    "dialCodes": [
      "+65"
    ]
  },
  "SH": {
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "dialCodes": [
      "+290",
      "+247"
    ]
  },
  "SI": {
    "name": "Slovenia",
    "dialCodes": [
      "+386"
    ]
  },
  "SJ": {
    "name": "Svalbard and Jan Mayen",
    "dialCodes": [
      "+47",
      "+4779"
    ]
  },
  "SK": {
    "name": "Slovakia",
    "dialCodes": [
      "+421"
    ]
  },
  "SL": {
    "name": "Sierra Leone",
    "dialCodes": [
      "+232"
    ]
  },
  "SM": {
    "name": "San Marino",
    "dialCodes": [
      "+378"
    ]
  },
  "SN": {
    "name": "Senegal",
    "dialCodes": [
      "+221"
    ]
  },
  "SO": {
    "name": "Somalia",
    "dialCodes": [
      "+252"
    ]
  },
  "SR": {
    "name": "Suriname",
    "dialCodes": [
      "+597"
    ]
  },
  "SS": {
    "name": "South Sudan",
    "dialCodes": [
      "+211"
    ]
  },
  "ST": {
    "name": "São Tomé and Príncipe",
    "dialCodes": [
      "+239"
    ]
  },
  "SV": {
    "name": "El Salvador",
    "dialCodes": [
      "+503"
    ]
  },
  "SX": {
    "name": "Sint Maarten",
    "dialCodes": [
      "+1",
      "+1721"
    ]
  },
  "SY": {
    "name": "Syria",
    "dialCodes": [
      "+963"
    ]
  },
  "SZ": {
    "name": "Eswatini",
    "dialCodes": [
      "+268"
    ]
  },
  "TA": {
    "name": "Tristan da Cunha",
    "dialCodes": [
      "+290"
    ]
  },
  "TC": {
    "name": "Turks and Caicos Islands",
    "dialCodes": [
      "+1",
      "+1649"
    ]
  },
  "TD": {
    "name": "Chad",
    "dialCodes": [
      "+235"
    ]
  },
  "TG": {
    "name": "Togo",
    "dialCodes": [
      "+228"
    ]
  },
  "TH": {
    "name": "Thailand",
    "dialCodes": [
      "+66"
    ]
  },
  "TJ": {
    "name": "Tajikistan",
    "dialCodes": [
      "+992"
    ]
  },
  "TK": {
    "name": "Tokelau",
    "dialCodes": [
      "+690"
    ]
  },
  "TL": {
    "name": "Timor-Leste",
    "dialCodes": [
      "+670"
    ]
  },
  "TM": {
    "name": "Turkmenistan",
    "dialCodes": [
      "+993"
    ]
  },
  "TN": {
    "name": "Tunisia",
    "dialCodes": [
      "+216"
    ]
  },
  "TO": {
    "name": "Tonga",
    "dialCodes": [
      "+676"
    ]
  },
  "TR": {
    "name": "Türkiye",
    "dialCodes": [
      "+90"
    ]
  },
  "TT": {
    "name": "Trinidad and Tobago",
    "dialCodes": [
      "+1",
      "+1868"
    ]
  },
  "TV": {
    "name": "Tuvalu",
    "dialCodes": [
      "+688"
    ]
  },
  "TW": {
    "name": "Taiwan",
    "dialCodes": [
      "+886"
    ]
  },
  "TZ": {
    "name": "Tanzania",
    "dialCodes": [
      "+255"
    ]
  },
  "UA": {
    "name": "Ukraine",
    "dialCodes": [
      "+380"
    ]
  },
  "UG": {
    "name": "Uganda",
    "dialCodes": [
      "+256"
    ]
  },
  "US": {
    "name": "United States",
    "dialCodes": [
      "+1",
      "+1201",
      "+1202",
      "+1203",
      "+1205",
      "+1206",
      "+1207",
      "+1208",
      "+1209",
      "+1210",
      "+1212",
      "+1213",
      "+1214",
      "+1215",
      "+1216",
      "+1217",
      "+1218",
      "+1219",
      "+1220",
      "+1223",
      "+1224",
      "+1225",
      "+1227",
      "+1228",
      "+1229",
      "+1231",
      "+1234",
      "+1239",
      "+1240",
      "+1248",
      "+1251",
      "+1252",
      "+1253",
      "+1254",
      "+1256",
      "+1260",
      "+1262",
      "+1267",
      "+1269",
      "+1270",
      "+1272",
      "+1274",
      "+1276",
      "+1279",
      "+1281",
      "+1283",
      "+1301",
      "+1302",
      "+1303",
      "+1304",
      "+1305",
      "+1307",
      "+1308",
      "+1309",
      "+1310",
      "+1312",
      "+1313",
      "+1314",
      "+1315",
      "+1316",
      "+1317",
      "+1318",
      "+1319",
      "+1320",
      "+1321",
      "+1323",
      "+1325",
      "+1326",
      "+1327",
      "+1330",
      "+1331",
      "+1332",
      "+1334",
      "+1336",
      "+1337",
      "+1339",
      "+1341",
      "+1346",
      "+1347",
      "+1351",
      "+1352",
      "+1360",
      "+1361",
      "+1364",
      "+1380",
      "+1385",
      "+1386",
      "+1401",
      "+1402",
      "+1404",
      "+1405",
      "+1406",
      "+1407",
      "+1408",
      "+1409",
      "+1410",
      "+1412",
      "+1413",
      "+1414",
      "+1415",
      "+1417",
      "+1419",
      "+1423",
      "+1424",
      "+1425",
      "+1430",
      "+1432",
      "+1434",
      "+1435",
      "+1440",
      "+1442",
      "+1443",
      "+1445",
      "+1447",
      "+1448",
      "+1458",
      "+1463",
      "+1464",
      "+1469",
      "+1470",
      "+1475",
      "+1478",
      "+1479",
      "+1480",
      "+1484",
      "+1500",
      "+1501",
      "+1502",
      "+1503",
      "+1504",
      "+1505",
      "+1507",
      "+1508",
      "+1509",
      "+1510",
      "+1512",
      "+1513",
      "+1515",
      "+1516",
      "+1517",
      "+1518",
      "+1520",
      "+1521",
      "+1522",
      "+1523",
      "+1524",
      "+1525",
      "+1526",
      "+1527",
      "+1528",
      "+1529",
      "+1530",
      "+1531",
      "+1532",
      "+1533",
      "+1534",
      "+1535",
      "+1538",
      "+1539",
      "+1540",
      "+1541",
      "+1542",
      "+1543",
      "+1544",
      "+1545",
      "+1546",
      "+1547",
      "+1549",
      "+1550",
      "+1551",
      "+1552",
      "+1553",
      "+1554",
      "+1556",
      "+1557",
      "+1558",
      "+1559",
      "+1561",
      "+1562",
      "+1563",
      "+1564",
      "+1566",
      "+1567",
      "+1569",
      "+1570",
      "+1571",
      "+1572",
      "+1573",
      "+1574",
      "+1575",
      "+1577",
      "+1578",
      "+1580",
      "+1582",
      "+1585",
      "+1586",
      "+1588",
      "+1589",
      "+1601",
      "+1602",
      "+1603",
      "+1605",
      "+1606",
      "+1607",
      "+1608",
      "+1609",
      "+1610",
      "+1612",
      "+1614",
      "+1615",
      "+1616",
      "+1617",
      "+1618",
      "+1619",
      "+1620",
      "+1623",
      "+1626",
      "+1628",
      "+1629",
      "+1630",
      "+1631",
      "+1636",
      "+1640",
      "+1641",
      "+1646",
      "+1650",
      "+1651",
      "+1656",
      "+1657",
      "+1659",
      "+1660",
      "+1661",
      "+1662",
      "+1667",
      "+1669",
      "+1678",
      "+1679",
      "+1680",
      "+1681",
      "+1682",
      "+1689",
      "+1700",
      "+1701",
      "+1702",
      "+1703",
      "+1704",
      "+1706",
      "+1707",
      "+1708",
      "+1710",
      "+1712",
      "+1713",
      "+1714",
      "+1715",
      "+1716",
      "+1717",
      "+1718",
      "+1719",
      "+1720",
      "+1724",
      "+1725",
      "+1726",
      "+1727",
      "+1730",
      "+1731",
      "+1732",
      "+1734",
      "+1737",
      "+1740",
      "+1743",
      "+1747",
      "+1754",
      "+1757",
      "+1760",
      "+1762",
      "+1763",
      "+1765",
      "+1769",
      "+1770",
      "+1771",
      "+1772",
      "+1773",
      "+1774",
      "+1775",
      "+1779",
      "+1781",
      "+1785",
      "+1786",
      "+1801",
      "+1802",
      "+1803",
      "+1804",
      "+1805",
      "+1806",
      "+1808",
      "+1810",
      "+1812",
      "+1813",
      "+1814",
      "+1815",
      "+1816",
      "+1817",
      "+1818",
      "+1820",
      "+1826",
      "+1828",
      "+1830",
      "+1831",
      "+1832",
      "+1838",
      "+1839",
      "+1840",
      "+1843",
      "+1845",
      "+1847",
      "+1848",
      "+1850",
      "+1854",
      "+1856",
      "+1857",
      "+1858",
      "+1859",
      "+1860",
      "+1862",
      "+1863",
      "+1864",
      "+1865",
      "+1870",
      "+1872",
      "+1878",
      "+1901",
      "+1903",
      "+1904",
      "+1906",
      "+1907",
      "+1908",
      "+1909",
      "+1910",
      "+1912",
      "+1913",
      "+1914",
      "+1915",
      "+1916",
      "+1917",
      "+1918",
      "+1919",
      "+1920",
      "+1925",
      "+1928",
      "+1929",
      "+1930",
      "+1931",
      "+1934",
      "+1936",
      "+1937",
      "+1938",
      "+1940",
      "+1941",
      "+1943",
      "+1945",
      "+1947",
      "+1948",
      "+1949",
      "+1951",
      "+1952",
      "+1954",
      "+1956",
      "+1959",
      "+1970",
      "+1971",
      "+1972",
      "+1973",
      "+1975",
      "+1978",
      "+1979",
      "+1980",
      "+1983",
      "+1984",
      "+1985",
      "+1986",
      "+1989"
    ]
  },
  "UY": {
    "name": "Uruguay",
    "dialCodes": [
      "+598"
    ]
  },
  "UZ": {
    "name": "Uzbekistan",
    "dialCodes": [
      "+998"
    ]
  },
  "VA": {
    "name": "Vatican City",
    "dialCodes": [
      "+39",
      "+3906698",
      "+379"
    ]
  },
  "VC": {
    "name": "Saint Vincent and the Grenadines",
    "dialCodes": [
      "+1",
      "+1784"
    ]
  },
  "VE": {
    "name": "Venezuela",
    "dialCodes": [
      "+58"
    ]
  },
  "VG": {
    "name": "British Virgin Islands",
    "dialCodes": [
      "+1",
      "+1284"
    ]
  },
  "VI": {
    "name": "United States Virgin Islands",
    "dialCodes": [
      "+1",
      "+1340"
    ]
  },
  "VN": {
    "name": "Vietnam",
    "dialCodes": [
      "+84"
    ]
  },
  "VU": {
    "name": "Vanuatu",
    "dialCodes": [
      "+678"
    ]
  },
  "WF": {
    "name": "Wallis and Futuna",
    "dialCodes": [
      "+681"
    ]
  },
  "WS": {
    "name": "Samoa",
    "dialCodes": [
      "+685"
    ]
  },
  "XK": {
    "name": "Kosovo",
    "dialCodes": [
      "+383"
    ]
  },
  "YE": {
    "name": "Yemen",
    "dialCodes": [
      "+967"
    ]
  },
  "YT": {
    "name": "Mayotte",
    "dialCodes": [
      "+262"
    ]
  },
  "ZA": {
    "name": "South Africa",
    "dialCodes": [
      "+27"
    ]
  },
  "ZM": {
    "name": "Zambia",
    "dialCodes": [
      "+260"
    ]
  },
  "ZW": {
    "name": "Zimbabwe",
    "dialCodes": [
      "+263"
    ]
  }
}
